namespace TriloGame.Game.Core.Progression;

// FeatureTreeData is the authored source of truth for all hard-coded feature trees.
// This file is intentionally written in a manual, tree-by-tree style so it can serve as
// the template for the real progression content we will author later.
internal static class FeatureTreeData
{
    public static IReadOnlyList<FeatureTree> BuildGlobalFeatureTrees()
    {
        var featureTrees = new List<FeatureTree>(28);

        // Tier 1: building
        var b1 = new FeatureTree("B1", "Building tier 1 feature tree.", ["building"], 1, []);
        var b1a = new SkillNode("B1-a", "B1 node a.");
        var b1b = new SkillNode("B1-b", "B1 node b.");
        var b1c = new SkillNode("B1-c", "B1 node c.");
        var b1d = new SkillNode("B1-d", "B1 node d.");
        var b1e = new SkillNode("B1-e", "B1 node e.");
        var b1f = new SkillNode("B1-f", "B1 node f.");
        var b1g = new SkillNode("B1-g", "B1 node g.");
        var b1h = new SkillNode("B1-h", "B1 node h.");
        b1.SetRoot(b1a);
        b1.AddChild(b1a, b1b);
        b1.AddChild(b1b, b1c);
        b1.AddChild(b1c, b1d);
        b1.AddChild(b1d, b1e);
        b1.AddChild(b1d, b1f);
        b1.AddChild(b1d, b1g);
        b1.AddChild(b1d, b1h);
        featureTrees.Add(b1);

        var b2 = new FeatureTree("B2", "Building tier 1 feature tree.", ["building"], 1, []);
        var b2a = new SkillNode("B2-a", "B2 node a.");
        var b2b = new SkillNode("B2-b", "B2 node b.");
        var b2c = new SkillNode("B2-c", "B2 node c.");
        var b2d = new SkillNode("B2-d", "B2 node d.");
        var b2e = new SkillNode("B2-e", "B2 node e.");
        var b2f = new SkillNode("B2-f", "B2 node f.");
        var b2v = new SkillNode("B2-v", "B2 node v.");
        var b2w = new SkillNode("B2-w", "B2 node w.");
        var b2x = new SkillNode("B2-x", "B2 node x.");
        var b2y = new SkillNode("B2-y", "B2 node y.");
        var b2z = new SkillNode("B2-z", "B2 node z.");
        b2.SetRoot(b2a);
        b2.AddChild(b2a, b2b);
        b2.AddChild(b2a, b2v);
        b2.AddChild(b2b, b2c);
        b2.AddChild(b2v, b2w);
        b2.AddChild(b2c, b2d);
        b2.AddChild(b2w, b2x);
        b2.AddChild(b2d, b2e);
        b2.AddChild(b2d, b2f);
        b2.AddChild(b2x, b2y);
        b2.AddChild(b2x, b2z);
        featureTrees.Add(b2);

        var b3 = new FeatureTree("B3", "Building tier 1 feature tree.", ["building"], 1, []);
        var b3a = new SkillNode("B3-a", "B3 node a.");
        var b3b = new SkillNode("B3-b", "B3 node b.");
        var b3c = new SkillNode("B3-c", "B3 node c.");
        var b3d = new SkillNode("B3-d", "B3 node d.");
        var b3e = new SkillNode("B3-e", "B3 node e.");
        var b3f = new SkillNode("B3-f", "B3 node f.");
        var b3g = new SkillNode("B3-g", "B3 node g.");
        var b3h = new SkillNode("B3-h", "B3 node h.");
        b3.SetRoot(b3a);
        b3.AddChild(b3a, b3b);
        b3.AddChild(b3b, b3c);
        b3.AddChild(b3b, b3f);
        b3.AddChild(b3c, b3d);
        b3.AddChild(b3f, b3g);
        b3.AddChild(b3d, b3e);
        b3.AddChild(b3g, b3h);
        featureTrees.Add(b3);

        // Tier 1: combat
        var c1 = new FeatureTree("C1", "Combat tier 1 feature tree.", ["combat"], 1, []);
        var c1a = new SkillNode("C1-a", "C1 node a.");
        var c1b = new SkillNode("C1-b", "C1 node b.");
        var c1c = new SkillNode("C1-c", "C1 node c.");
        var c1d = new SkillNode("C1-d", "C1 node d.");
        var c1e = new SkillNode("C1-e", "C1 node e.");
        var c1f = new SkillNode("C1-f", "C1 node f.");
        var c1g = new SkillNode("C1-g", "C1 node g.");
        var c1h = new SkillNode("C1-h", "C1 node h.");
        c1.SetRoot(c1a);
        c1.AddChild(c1a, c1b);
        c1.AddChild(c1b, c1c);
        c1.AddChild(c1c, c1d);
        c1.AddChild(c1d, c1e);
        c1.AddChild(c1d, c1f);
        c1.AddChild(c1d, c1g);
        c1.AddChild(c1d, c1h);
        featureTrees.Add(c1);

        var c2 = new FeatureTree("C2", "Combat tier 1 feature tree.", ["combat"], 1, []);
        var c2a = new SkillNode("C2-a", "C2 node a.");
        var c2b = new SkillNode("C2-b", "C2 node b.");
        var c2c = new SkillNode("C2-c", "C2 node c.");
        var c2d = new SkillNode("C2-d", "C2 node d.");
        var c2e = new SkillNode("C2-e", "C2 node e.");
        var c2f = new SkillNode("C2-f", "C2 node f.");
        var c2v = new SkillNode("C2-v", "C2 node v.");
        var c2w = new SkillNode("C2-w", "C2 node w.");
        var c2x = new SkillNode("C2-x", "C2 node x.");
        var c2y = new SkillNode("C2-y", "C2 node y.");
        var c2z = new SkillNode("C2-z", "C2 node z.");
        c2.SetRoot(c2a);
        c2.AddChild(c2a, c2b);
        c2.AddChild(c2a, c2v);
        c2.AddChild(c2b, c2c);
        c2.AddChild(c2v, c2w);
        c2.AddChild(c2c, c2d);
        c2.AddChild(c2w, c2x);
        c2.AddChild(c2d, c2e);
        c2.AddChild(c2d, c2f);
        c2.AddChild(c2x, c2y);
        c2.AddChild(c2x, c2z);
        featureTrees.Add(c2);

        var c3 = new FeatureTree("C3", "Combat tier 1 feature tree.", ["combat"], 1, []);
        var c3a = new SkillNode("C3-a", "C3 node a.");
        var c3b = new SkillNode("C3-b", "C3 node b.");
        var c3c = new SkillNode("C3-c", "C3 node c.");
        var c3d = new SkillNode("C3-d", "C3 node d.");
        var c3e = new SkillNode("C3-e", "C3 node e.");
        var c3f = new SkillNode("C3-f", "C3 node f.");
        var c3g = new SkillNode("C3-g", "C3 node g.");
        var c3h = new SkillNode("C3-h", "C3 node h.");
        c3.SetRoot(c3a);
        c3.AddChild(c3a, c3b);
        c3.AddChild(c3b, c3c);
        c3.AddChild(c3b, c3f);
        c3.AddChild(c3c, c3d);
        c3.AddChild(c3f, c3g);
        c3.AddChild(c3d, c3e);
        c3.AddChild(c3g, c3h);
        featureTrees.Add(c3);

        // Tier 1: farming
        var f1 = new FeatureTree("F1", "Farming tier 1 feature tree.", ["farming"], 1, []);
        var f1a = new SkillNode("F1-a", "F1 node a.");
        var f1b = new SkillNode("F1-b", "F1 node b.");
        var f1c = new SkillNode("F1-c", "F1 node c.");
        var f1d = new SkillNode("F1-d", "F1 node d.");
        var f1e = new SkillNode("F1-e", "F1 node e.");
        var f1f = new SkillNode("F1-f", "F1 node f.");
        var f1g = new SkillNode("F1-g", "F1 node g.");
        var f1h = new SkillNode("F1-h", "F1 node h.");
        f1.SetRoot(f1a);
        f1.AddChild(f1a, f1b);
        f1.AddChild(f1b, f1c);
        f1.AddChild(f1c, f1d);
        f1.AddChild(f1d, f1e);
        f1.AddChild(f1d, f1f);
        f1.AddChild(f1d, f1g);
        f1.AddChild(f1d, f1h);
        featureTrees.Add(f1);

        var f2 = new FeatureTree("F2", "Farming tier 1 feature tree.", ["farming"], 1, []);
        var f2a = new SkillNode("F2-a", "F2 node a.");
        var f2b = new SkillNode("F2-b", "F2 node b.");
        var f2c = new SkillNode("F2-c", "F2 node c.");
        var f2d = new SkillNode("F2-d", "F2 node d.");
        var f2e = new SkillNode("F2-e", "F2 node e.");
        var f2f = new SkillNode("F2-f", "F2 node f.");
        var f2v = new SkillNode("F2-v", "F2 node v.");
        var f2w = new SkillNode("F2-w", "F2 node w.");
        var f2x = new SkillNode("F2-x", "F2 node x.");
        var f2y = new SkillNode("F2-y", "F2 node y.");
        var f2z = new SkillNode("F2-z", "F2 node z.");
        f2.SetRoot(f2a);
        f2.AddChild(f2a, f2b);
        f2.AddChild(f2a, f2v);
        f2.AddChild(f2b, f2c);
        f2.AddChild(f2v, f2w);
        f2.AddChild(f2c, f2d);
        f2.AddChild(f2w, f2x);
        f2.AddChild(f2d, f2e);
        f2.AddChild(f2d, f2f);
        f2.AddChild(f2x, f2y);
        f2.AddChild(f2x, f2z);
        featureTrees.Add(f2);

        var f3 = new FeatureTree("F3", "Farming tier 1 feature tree.", ["farming"], 1, []);
        var f3a = new SkillNode("F3-a", "F3 node a.");
        var f3b = new SkillNode("F3-b", "F3 node b.");
        var f3c = new SkillNode("F3-c", "F3 node c.");
        var f3d = new SkillNode("F3-d", "F3 node d.");
        var f3e = new SkillNode("F3-e", "F3 node e.");
        var f3f = new SkillNode("F3-f", "F3 node f.");
        var f3g = new SkillNode("F3-g", "F3 node g.");
        var f3h = new SkillNode("F3-h", "F3 node h.");
        f3.SetRoot(f3a);
        f3.AddChild(f3a, f3b);
        f3.AddChild(f3b, f3c);
        f3.AddChild(f3b, f3f);
        f3.AddChild(f3c, f3d);
        f3.AddChild(f3f, f3g);
        f3.AddChild(f3d, f3e);
        f3.AddChild(f3g, f3h);
        featureTrees.Add(f3);

        // Tier 1: mining
        var m1 = new FeatureTree("M1", "Mining tier 1 feature tree.", ["mining"], 1, []);
        var m1a = new SkillNode("M1-a", "M1 node a.");
        var m1b = new SkillNode("M1-b", "M1 node b.");
        var m1c = new SkillNode("M1-c", "M1 node c.");
        var m1d = new SkillNode("M1-d", "M1 node d.");
        var m1e = new SkillNode("M1-e", "M1 node e.");
        var m1f = new SkillNode("M1-f", "M1 node f.");
        var m1g = new SkillNode("M1-g", "M1 node g.");
        var m1h = new SkillNode("M1-h", "M1 node h.");
        m1.SetRoot(m1a);
        m1.AddChild(m1a, m1b);
        m1.AddChild(m1b, m1c);
        m1.AddChild(m1c, m1d);
        m1.AddChild(m1d, m1e);
        m1.AddChild(m1d, m1f);
        m1.AddChild(m1d, m1g);
        m1.AddChild(m1d, m1h);
        featureTrees.Add(m1);

        var m2 = new FeatureTree("M2", "Mining tier 1 feature tree.", ["mining"], 1, []);
        var m2a = new SkillNode("M2-a", "M2 node a.");
        var m2b = new SkillNode("M2-b", "M2 node b.");
        var m2c = new SkillNode("M2-c", "M2 node c.");
        var m2d = new SkillNode("M2-d", "M2 node d.");
        var m2e = new SkillNode("M2-e", "M2 node e.");
        var m2f = new SkillNode("M2-f", "M2 node f.");
        var m2v = new SkillNode("M2-v", "M2 node v.");
        var m2w = new SkillNode("M2-w", "M2 node w.");
        var m2x = new SkillNode("M2-x", "M2 node x.");
        var m2y = new SkillNode("M2-y", "M2 node y.");
        var m2z = new SkillNode("M2-z", "M2 node z.");
        m2.SetRoot(m2a);
        m2.AddChild(m2a, m2b);
        m2.AddChild(m2a, m2v);
        m2.AddChild(m2b, m2c);
        m2.AddChild(m2v, m2w);
        m2.AddChild(m2c, m2d);
        m2.AddChild(m2w, m2x);
        m2.AddChild(m2d, m2e);
        m2.AddChild(m2d, m2f);
        m2.AddChild(m2x, m2y);
        m2.AddChild(m2x, m2z);
        featureTrees.Add(m2);

        var m3 = new FeatureTree("M3", "Mining tier 1 feature tree.", ["mining"], 1, []);
        var m3a = new SkillNode("M3-a", "M3 node a.");
        var m3b = new SkillNode("M3-b", "M3 node b.");
        var m3c = new SkillNode("M3-c", "M3 node c.");
        var m3d = new SkillNode("M3-d", "M3 node d.");
        var m3e = new SkillNode("M3-e", "M3 node e.");
        var m3f = new SkillNode("M3-f", "M3 node f.");
        var m3g = new SkillNode("M3-g", "M3 node g.");
        var m3h = new SkillNode("M3-h", "M3 node h.");
        m3.SetRoot(m3a);
        m3.AddChild(m3a, m3b);
        m3.AddChild(m3b, m3c);
        m3.AddChild(m3b, m3f);
        m3.AddChild(m3c, m3d);
        m3.AddChild(m3f, m3g);
        m3.AddChild(m3d, m3e);
        m3.AddChild(m3g, m3h);
        featureTrees.Add(m3);

        // Tier 2: building + combat
        var bc1 = new FeatureTree("BC1", "Building and combat tier 2 feature tree.", ["building", "combat"], 2, ["B1", "C1"]);
        var bc1a = new SkillNode("BC1-a", "BC1 node a.");
        var bc1b = new SkillNode("BC1-b", "BC1 node b.");
        var bc1c = new SkillNode("BC1-c", "BC1 node c.");
        var bc1d = new SkillNode("BC1-d", "BC1 node d.");
        var bc1e = new SkillNode("BC1-e", "BC1 node e.");
        var bc1f = new SkillNode("BC1-f", "BC1 node f.");
        var bc1g = new SkillNode("BC1-g", "BC1 node g.");
        var bc1h = new SkillNode("BC1-h", "BC1 node h.");
        bc1.SetRoot(bc1a);
        bc1.AddChild(bc1a, bc1b);
        bc1.AddChild(bc1b, bc1c);
        bc1.AddChild(bc1c, bc1d);
        bc1.AddChild(bc1d, bc1e);
        bc1.AddChild(bc1d, bc1f);
        bc1.AddChild(bc1d, bc1g);
        bc1.AddChild(bc1d, bc1h);
        featureTrees.Add(bc1);

        var bc2 = new FeatureTree("BC2", "Building and combat tier 2 feature tree.", ["building", "combat"], 2, ["B1", "C1"]);
        var bc2a = new SkillNode("BC2-a", "BC2 node a.");
        var bc2b = new SkillNode("BC2-b", "BC2 node b.");
        var bc2c = new SkillNode("BC2-c", "BC2 node c.");
        var bc2d = new SkillNode("BC2-d", "BC2 node d.");
        var bc2e = new SkillNode("BC2-e", "BC2 node e.");
        var bc2f = new SkillNode("BC2-f", "BC2 node f.");
        var bc2v = new SkillNode("BC2-v", "BC2 node v.");
        var bc2w = new SkillNode("BC2-w", "BC2 node w.");
        var bc2x = new SkillNode("BC2-x", "BC2 node x.");
        var bc2y = new SkillNode("BC2-y", "BC2 node y.");
        var bc2z = new SkillNode("BC2-z", "BC2 node z.");
        bc2.SetRoot(bc2a);
        bc2.AddChild(bc2a, bc2b);
        bc2.AddChild(bc2a, bc2v);
        bc2.AddChild(bc2b, bc2c);
        bc2.AddChild(bc2v, bc2w);
        bc2.AddChild(bc2c, bc2d);
        bc2.AddChild(bc2w, bc2x);
        bc2.AddChild(bc2d, bc2e);
        bc2.AddChild(bc2d, bc2f);
        bc2.AddChild(bc2x, bc2y);
        bc2.AddChild(bc2x, bc2z);
        featureTrees.Add(bc2);

        // Tier 2: building + farming
        var bf1 = new FeatureTree("BF1", "Building and farming tier 2 feature tree.", ["building", "farming"], 2, ["B1", "F1"]);
        var bf1a = new SkillNode("BF1-a", "BF1 node a.");
        var bf1b = new SkillNode("BF1-b", "BF1 node b.");
        var bf1c = new SkillNode("BF1-c", "BF1 node c.");
        var bf1d = new SkillNode("BF1-d", "BF1 node d.");
        var bf1e = new SkillNode("BF1-e", "BF1 node e.");
        var bf1f = new SkillNode("BF1-f", "BF1 node f.");
        var bf1g = new SkillNode("BF1-g", "BF1 node g.");
        var bf1h = new SkillNode("BF1-h", "BF1 node h.");
        bf1.SetRoot(bf1a);
        bf1.AddChild(bf1a, bf1b);
        bf1.AddChild(bf1b, bf1c);
        bf1.AddChild(bf1c, bf1d);
        bf1.AddChild(bf1d, bf1e);
        bf1.AddChild(bf1d, bf1f);
        bf1.AddChild(bf1d, bf1g);
        bf1.AddChild(bf1d, bf1h);
        featureTrees.Add(bf1);

        var bf2 = new FeatureTree("BF2", "Building and farming tier 2 feature tree.", ["building", "farming"], 2, ["B1", "F1"]);
        var bf2a = new SkillNode("BF2-a", "BF2 node a.");
        var bf2b = new SkillNode("BF2-b", "BF2 node b.");
        var bf2c = new SkillNode("BF2-c", "BF2 node c.");
        var bf2d = new SkillNode("BF2-d", "BF2 node d.");
        var bf2e = new SkillNode("BF2-e", "BF2 node e.");
        var bf2f = new SkillNode("BF2-f", "BF2 node f.");
        var bf2v = new SkillNode("BF2-v", "BF2 node v.");
        var bf2w = new SkillNode("BF2-w", "BF2 node w.");
        var bf2x = new SkillNode("BF2-x", "BF2 node x.");
        var bf2y = new SkillNode("BF2-y", "BF2 node y.");
        var bf2z = new SkillNode("BF2-z", "BF2 node z.");
        bf2.SetRoot(bf2a);
        bf2.AddChild(bf2a, bf2b);
        bf2.AddChild(bf2a, bf2v);
        bf2.AddChild(bf2b, bf2c);
        bf2.AddChild(bf2v, bf2w);
        bf2.AddChild(bf2c, bf2d);
        bf2.AddChild(bf2w, bf2x);
        bf2.AddChild(bf2d, bf2e);
        bf2.AddChild(bf2d, bf2f);
        bf2.AddChild(bf2x, bf2y);
        bf2.AddChild(bf2x, bf2z);
        featureTrees.Add(bf2);

        // Tier 2: building + mining
        var bm1 = new FeatureTree("BM1", "Building and mining tier 2 feature tree.", ["building", "mining"], 2, ["B1", "M1"]);
        var bm1a = new SkillNode("BM1-a", "BM1 node a.");
        var bm1b = new SkillNode("BM1-b", "BM1 node b.");
        var bm1c = new SkillNode("BM1-c", "BM1 node c.");
        var bm1d = new SkillNode("BM1-d", "BM1 node d.");
        var bm1e = new SkillNode("BM1-e", "BM1 node e.");
        var bm1f = new SkillNode("BM1-f", "BM1 node f.");
        var bm1g = new SkillNode("BM1-g", "BM1 node g.");
        var bm1h = new SkillNode("BM1-h", "BM1 node h.");
        bm1.SetRoot(bm1a);
        bm1.AddChild(bm1a, bm1b);
        bm1.AddChild(bm1b, bm1c);
        bm1.AddChild(bm1c, bm1d);
        bm1.AddChild(bm1d, bm1e);
        bm1.AddChild(bm1d, bm1f);
        bm1.AddChild(bm1d, bm1g);
        bm1.AddChild(bm1d, bm1h);
        featureTrees.Add(bm1);

        var bm2 = new FeatureTree("BM2", "Building and mining tier 2 feature tree.", ["building", "mining"], 2, ["B1", "M1"]);
        var bm2a = new SkillNode("BM2-a", "BM2 node a.");
        var bm2b = new SkillNode("BM2-b", "BM2 node b.");
        var bm2c = new SkillNode("BM2-c", "BM2 node c.");
        var bm2d = new SkillNode("BM2-d", "BM2 node d.");
        var bm2e = new SkillNode("BM2-e", "BM2 node e.");
        var bm2f = new SkillNode("BM2-f", "BM2 node f.");
        var bm2v = new SkillNode("BM2-v", "BM2 node v.");
        var bm2w = new SkillNode("BM2-w", "BM2 node w.");
        var bm2x = new SkillNode("BM2-x", "BM2 node x.");
        var bm2y = new SkillNode("BM2-y", "BM2 node y.");
        var bm2z = new SkillNode("BM2-z", "BM2 node z.");
        bm2.SetRoot(bm2a);
        bm2.AddChild(bm2a, bm2b);
        bm2.AddChild(bm2a, bm2v);
        bm2.AddChild(bm2b, bm2c);
        bm2.AddChild(bm2v, bm2w);
        bm2.AddChild(bm2c, bm2d);
        bm2.AddChild(bm2w, bm2x);
        bm2.AddChild(bm2d, bm2e);
        bm2.AddChild(bm2d, bm2f);
        bm2.AddChild(bm2x, bm2y);
        bm2.AddChild(bm2x, bm2z);
        featureTrees.Add(bm2);

        // Tier 2: combat + farming
        var cf1 = new FeatureTree("CF1", "Combat and farming tier 2 feature tree.", ["combat", "farming"], 2, ["C1", "F1"]);
        var cf1a = new SkillNode("CF1-a", "CF1 node a.");
        var cf1b = new SkillNode("CF1-b", "CF1 node b.");
        var cf1c = new SkillNode("CF1-c", "CF1 node c.");
        var cf1d = new SkillNode("CF1-d", "CF1 node d.");
        var cf1e = new SkillNode("CF1-e", "CF1 node e.");
        var cf1f = new SkillNode("CF1-f", "CF1 node f.");
        var cf1g = new SkillNode("CF1-g", "CF1 node g.");
        var cf1h = new SkillNode("CF1-h", "CF1 node h.");
        cf1.SetRoot(cf1a);
        cf1.AddChild(cf1a, cf1b);
        cf1.AddChild(cf1b, cf1c);
        cf1.AddChild(cf1c, cf1d);
        cf1.AddChild(cf1d, cf1e);
        cf1.AddChild(cf1d, cf1f);
        cf1.AddChild(cf1d, cf1g);
        cf1.AddChild(cf1d, cf1h);
        featureTrees.Add(cf1);

        var cf2 = new FeatureTree("CF2", "Combat and farming tier 2 feature tree.", ["combat", "farming"], 2, ["C1", "F1"]);
        var cf2a = new SkillNode("CF2-a", "CF2 node a.");
        var cf2b = new SkillNode("CF2-b", "CF2 node b.");
        var cf2c = new SkillNode("CF2-c", "CF2 node c.");
        var cf2d = new SkillNode("CF2-d", "CF2 node d.");
        var cf2e = new SkillNode("CF2-e", "CF2 node e.");
        var cf2f = new SkillNode("CF2-f", "CF2 node f.");
        var cf2v = new SkillNode("CF2-v", "CF2 node v.");
        var cf2w = new SkillNode("CF2-w", "CF2 node w.");
        var cf2x = new SkillNode("CF2-x", "CF2 node x.");
        var cf2y = new SkillNode("CF2-y", "CF2 node y.");
        var cf2z = new SkillNode("CF2-z", "CF2 node z.");
        cf2.SetRoot(cf2a);
        cf2.AddChild(cf2a, cf2b);
        cf2.AddChild(cf2a, cf2v);
        cf2.AddChild(cf2b, cf2c);
        cf2.AddChild(cf2v, cf2w);
        cf2.AddChild(cf2c, cf2d);
        cf2.AddChild(cf2w, cf2x);
        cf2.AddChild(cf2d, cf2e);
        cf2.AddChild(cf2d, cf2f);
        cf2.AddChild(cf2x, cf2y);
        cf2.AddChild(cf2x, cf2z);
        featureTrees.Add(cf2);

        // Tier 2: combat + mining
        var cm1 = new FeatureTree("CM1", "Combat and mining tier 2 feature tree.", ["combat", "mining"], 2, ["C1", "M1"]);
        var cm1a = new SkillNode("CM1-a", "CM1 node a.");
        var cm1b = new SkillNode("CM1-b", "CM1 node b.");
        var cm1c = new SkillNode("CM1-c", "CM1 node c.");
        var cm1d = new SkillNode("CM1-d", "CM1 node d.");
        var cm1e = new SkillNode("CM1-e", "CM1 node e.");
        var cm1f = new SkillNode("CM1-f", "CM1 node f.");
        var cm1g = new SkillNode("CM1-g", "CM1 node g.");
        var cm1h = new SkillNode("CM1-h", "CM1 node h.");
        cm1.SetRoot(cm1a);
        cm1.AddChild(cm1a, cm1b);
        cm1.AddChild(cm1b, cm1c);
        cm1.AddChild(cm1c, cm1d);
        cm1.AddChild(cm1d, cm1e);
        cm1.AddChild(cm1d, cm1f);
        cm1.AddChild(cm1d, cm1g);
        cm1.AddChild(cm1d, cm1h);
        featureTrees.Add(cm1);

        var cm2 = new FeatureTree("CM2", "Combat and mining tier 2 feature tree.", ["combat", "mining"], 2, ["C1", "M1"]);
        var cm2a = new SkillNode("CM2-a", "CM2 node a.");
        var cm2b = new SkillNode("CM2-b", "CM2 node b.");
        var cm2c = new SkillNode("CM2-c", "CM2 node c.");
        var cm2d = new SkillNode("CM2-d", "CM2 node d.");
        var cm2e = new SkillNode("CM2-e", "CM2 node e.");
        var cm2f = new SkillNode("CM2-f", "CM2 node f.");
        var cm2v = new SkillNode("CM2-v", "CM2 node v.");
        var cm2w = new SkillNode("CM2-w", "CM2 node w.");
        var cm2x = new SkillNode("CM2-x", "CM2 node x.");
        var cm2y = new SkillNode("CM2-y", "CM2 node y.");
        var cm2z = new SkillNode("CM2-z", "CM2 node z.");
        cm2.SetRoot(cm2a);
        cm2.AddChild(cm2a, cm2b);
        cm2.AddChild(cm2a, cm2v);
        cm2.AddChild(cm2b, cm2c);
        cm2.AddChild(cm2v, cm2w);
        cm2.AddChild(cm2c, cm2d);
        cm2.AddChild(cm2w, cm2x);
        cm2.AddChild(cm2d, cm2e);
        cm2.AddChild(cm2d, cm2f);
        cm2.AddChild(cm2x, cm2y);
        cm2.AddChild(cm2x, cm2z);
        featureTrees.Add(cm2);

        // Tier 2: farming + mining
        var fm1 = new FeatureTree("FM1", "Farming and mining tier 2 feature tree.", ["farming", "mining"], 2, ["F1", "M1"]);
        var fm1a = new SkillNode("FM1-a", "FM1 node a.");
        var fm1b = new SkillNode("FM1-b", "FM1 node b.");
        var fm1c = new SkillNode("FM1-c", "FM1 node c.");
        var fm1d = new SkillNode("FM1-d", "FM1 node d.");
        var fm1e = new SkillNode("FM1-e", "FM1 node e.");
        var fm1f = new SkillNode("FM1-f", "FM1 node f.");
        var fm1g = new SkillNode("FM1-g", "FM1 node g.");
        var fm1h = new SkillNode("FM1-h", "FM1 node h.");
        fm1.SetRoot(fm1a);
        fm1.AddChild(fm1a, fm1b);
        fm1.AddChild(fm1b, fm1c);
        fm1.AddChild(fm1c, fm1d);
        fm1.AddChild(fm1d, fm1e);
        fm1.AddChild(fm1d, fm1f);
        fm1.AddChild(fm1d, fm1g);
        fm1.AddChild(fm1d, fm1h);
        featureTrees.Add(fm1);

        var fm2 = new FeatureTree("FM2", "Farming and mining tier 2 feature tree.", ["farming", "mining"], 2, ["F1", "M1"]);
        var fm2a = new SkillNode("FM2-a", "FM2 node a.");
        var fm2b = new SkillNode("FM2-b", "FM2 node b.");
        var fm2c = new SkillNode("FM2-c", "FM2 node c.");
        var fm2d = new SkillNode("FM2-d", "FM2 node d.");
        var fm2e = new SkillNode("FM2-e", "FM2 node e.");
        var fm2f = new SkillNode("FM2-f", "FM2 node f.");
        var fm2v = new SkillNode("FM2-v", "FM2 node v.");
        var fm2w = new SkillNode("FM2-w", "FM2 node w.");
        var fm2x = new SkillNode("FM2-x", "FM2 node x.");
        var fm2y = new SkillNode("FM2-y", "FM2 node y.");
        var fm2z = new SkillNode("FM2-z", "FM2 node z.");
        fm2.SetRoot(fm2a);
        fm2.AddChild(fm2a, fm2b);
        fm2.AddChild(fm2a, fm2v);
        fm2.AddChild(fm2b, fm2c);
        fm2.AddChild(fm2v, fm2w);
        fm2.AddChild(fm2c, fm2d);
        fm2.AddChild(fm2w, fm2x);
        fm2.AddChild(fm2d, fm2e);
        fm2.AddChild(fm2d, fm2f);
        fm2.AddChild(fm2x, fm2y);
        fm2.AddChild(fm2x, fm2z);
        featureTrees.Add(fm2);

        // Tier 3: building + combat + farming
        var bcf1 = new FeatureTree("BCF1", "Building, combat, and farming tier 3 feature tree.", ["building", "combat", "farming"], 3, ["BC1", "BF1", "CF1"]);
        var bcf1a = new SkillNode("BCF1-a", "BCF1 node a.");
        var bcf1b = new SkillNode("BCF1-b", "BCF1 node b.");
        var bcf1c = new SkillNode("BCF1-c", "BCF1 node c.");
        var bcf1d = new SkillNode("BCF1-d", "BCF1 node d.");
        var bcf1e = new SkillNode("BCF1-e", "BCF1 node e.");
        var bcf1f = new SkillNode("BCF1-f", "BCF1 node f.");
        var bcf1g = new SkillNode("BCF1-g", "BCF1 node g.");
        var bcf1h = new SkillNode("BCF1-h", "BCF1 node h.");
        bcf1.SetRoot(bcf1a);
        bcf1.AddChild(bcf1a, bcf1b);
        bcf1.AddChild(bcf1b, bcf1c);
        bcf1.AddChild(bcf1b, bcf1f);
        bcf1.AddChild(bcf1c, bcf1d);
        bcf1.AddChild(bcf1f, bcf1g);
        bcf1.AddChild(bcf1d, bcf1e);
        bcf1.AddChild(bcf1g, bcf1h);
        featureTrees.Add(bcf1);

        // Tier 3: building + combat + mining
        var bcm1 = new FeatureTree("BCM1", "Building, combat, and mining tier 3 feature tree.", ["building", "combat", "mining"], 3, ["BC1", "BM1", "CM1"]);
        var bcm1a = new SkillNode("BCM1-a", "BCM1 node a.");
        var bcm1b = new SkillNode("BCM1-b", "BCM1 node b.");
        var bcm1c = new SkillNode("BCM1-c", "BCM1 node c.");
        var bcm1d = new SkillNode("BCM1-d", "BCM1 node d.");
        var bcm1e = new SkillNode("BCM1-e", "BCM1 node e.");
        var bcm1f = new SkillNode("BCM1-f", "BCM1 node f.");
        var bcm1g = new SkillNode("BCM1-g", "BCM1 node g.");
        var bcm1h = new SkillNode("BCM1-h", "BCM1 node h.");
        bcm1.SetRoot(bcm1a);
        bcm1.AddChild(bcm1a, bcm1b);
        bcm1.AddChild(bcm1b, bcm1c);
        bcm1.AddChild(bcm1b, bcm1f);
        bcm1.AddChild(bcm1c, bcm1d);
        bcm1.AddChild(bcm1f, bcm1g);
        bcm1.AddChild(bcm1d, bcm1e);
        bcm1.AddChild(bcm1g, bcm1h);
        featureTrees.Add(bcm1);

        // Tier 3: building + farming + mining
        var bfm1 = new FeatureTree("BFM1", "Building, farming, and mining tier 3 feature tree.", ["building", "farming", "mining"], 3, ["BF1", "BM1", "FM1"]);
        var bfm1a = new SkillNode("BFM1-a", "BFM1 node a.");
        var bfm1b = new SkillNode("BFM1-b", "BFM1 node b.");
        var bfm1c = new SkillNode("BFM1-c", "BFM1 node c.");
        var bfm1d = new SkillNode("BFM1-d", "BFM1 node d.");
        var bfm1e = new SkillNode("BFM1-e", "BFM1 node e.");
        var bfm1f = new SkillNode("BFM1-f", "BFM1 node f.");
        var bfm1g = new SkillNode("BFM1-g", "BFM1 node g.");
        var bfm1h = new SkillNode("BFM1-h", "BFM1 node h.");
        bfm1.SetRoot(bfm1a);
        bfm1.AddChild(bfm1a, bfm1b);
        bfm1.AddChild(bfm1b, bfm1c);
        bfm1.AddChild(bfm1b, bfm1f);
        bfm1.AddChild(bfm1c, bfm1d);
        bfm1.AddChild(bfm1f, bfm1g);
        bfm1.AddChild(bfm1d, bfm1e);
        bfm1.AddChild(bfm1g, bfm1h);
        featureTrees.Add(bfm1);

        // Tier 3: combat + farming + mining
        var cfm1 = new FeatureTree("CFM1", "Combat, farming, and mining tier 3 feature tree.", ["combat", "farming", "mining"], 3, ["CF1", "CM1", "FM1"]);
        var cfm1a = new SkillNode("CFM1-a", "CFM1 node a.");
        var cfm1b = new SkillNode("CFM1-b", "CFM1 node b.");
        var cfm1c = new SkillNode("CFM1-c", "CFM1 node c.");
        var cfm1d = new SkillNode("CFM1-d", "CFM1 node d.");
        var cfm1e = new SkillNode("CFM1-e", "CFM1 node e.");
        var cfm1f = new SkillNode("CFM1-f", "CFM1 node f.");
        var cfm1g = new SkillNode("CFM1-g", "CFM1 node g.");
        var cfm1h = new SkillNode("CFM1-h", "CFM1 node h.");
        cfm1.SetRoot(cfm1a);
        cfm1.AddChild(cfm1a, cfm1b);
        cfm1.AddChild(cfm1b, cfm1c);
        cfm1.AddChild(cfm1b, cfm1f);
        cfm1.AddChild(cfm1c, cfm1d);
        cfm1.AddChild(cfm1f, cfm1g);
        cfm1.AddChild(cfm1d, cfm1e);
        cfm1.AddChild(cfm1g, cfm1h);
        featureTrees.Add(cfm1);

        return featureTrees;
    }
}
