<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TriloGame.Game\TriloGame.Game.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tmp\**\*.cs" />
    <EmbeddedResource Remove="tmp\**\*" />
    <None Remove="tmp\**\*" />
    <Content Remove="tmp\**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\TriloGame.Game\Content\Fonts\Display\TrebuchetDisplay48.fnt" Link="Content\Fonts\Display\TrebuchetDisplay48.fnt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\TriloGame.Game\Content\Fonts\Display\TrebuchetDisplay48_0.png" Link="Content\Fonts\Display\TrebuchetDisplay48_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
